---
title: "Power_calculation"
author: "Kenneth Matreyek"
date: '2022-09-20'
output: html_document
---

```{r Import libraries}
library(tidyverse)
```

```{r SORT-seq data}
rm(list = ls())
 
## values range from 0 to 1
## median standard deviation is 0.15 (From ACE2 Kozak experiments)

## GCCACCATG is 0.6625684
## TTATGGATG is 0.3269816

high_val <- 0.6625684
low_val <- 0.3269816
med_val <- mean(c(low_val,high_val))
sd_val <- 0.15

high_dist <- rnorm(mean = high_val, sd = sd_val, n = 100000)
low_dist <- rnorm(mean = low_val, sd = sd_val, n = 100000)
med_dist <- rnorm(mean = med_val, sd = sd_val, n = 100000)

ggplot() + geom_density(aes(x = high_dist)) + geom_density(aes(x = low_dist), color = "red") + geom_density(aes(x = med_dist), color = "blue")

replicate_n_vector <- seq(2,7)
multiverse_number <- 20000 ## Large but not crazy number

multiverse_counter <- c()
multiverse_results_n <- c()
multiverse_results_low <- c()
multiverse_results_med <- c()

for( y in 1:multiverse_number){
  replicate_results_n <- c()
  replicate_results_low <- c()
  replicate_results_med <- c()
  for(x in replicate_n_vector){
    high <- mean(sample(high_dist, x, replace = T))
    low <- mean(sample(low_dist, x), replace = T)
    med <- mean(sample(med_dist, x), replace = T)
    result_low <- high - low
    result_med <- high - med
    replicate_results_n <- c(replicate_results_n, x)
    replicate_results_low <- c(replicate_results_low,result_low)
    replicate_results_med <- c(replicate_results_med,result_med)
  }
  replicate_date_frame <- data.frame("replicates" = replicate_results_n, "low" = replicate_results_low, "med" = replicate_results_med)
  multiverse_counter <- c(multiverse_counter, y)
  multiverse_results_n <- c(multiverse_results_n,replicate_results_n)
  multiverse_results_low <- c(multiverse_results_low,replicate_results_low)
  multiverse_results_med <- c(multiverse_results_med,replicate_results_med)
}
multiverse_date_frame <- data.frame("multiverse_number" = multiverse_counter,"replicate" = multiverse_results_n, "low" = multiverse_results_low, "med" = multiverse_results_med)

multiverse_date_frame$low_pos <- as.numeric(multiverse_date_frame$low > 0)
multiverse_date_frame$med_pos <- as.numeric(multiverse_date_frame$med > 0)

multiverse_date_frame_summary <- multiverse_date_frame %>% group_by(replicate) %>% summarize(low_pct = sum(low_pos), med_pct = sum(med_pos)) %>% mutate(low_pct = low_pct / multiverse_number, med_pct = med_pct / multiverse_number)

variant_ranges <- c(100,300,1000,3000,10000,30000,100000)
  
variant_results_variant_num <- c()
variant_results_replicate_num <- c()
variant_results_low_miscalled <- c()
variant_results_med_miscalled <- c()

for(z in variant_ranges){
  for(w in 1:nrow(multiverse_date_frame_summary)){
    low_correct <- sample(x = c(0,1), size = z, prob = c((1-multiverse_date_frame_summary$low_pct[w]),multiverse_date_frame_summary$low_pct[w]), replace = T)
    variant_results_low_miscalled <- c(variant_results_low_miscalled,z - sum(low_correct))
    med_correct <- sample(x = c(0,1), size = z, prob = c((1-multiverse_date_frame_summary$low_pct[w]),multiverse_date_frame_summary$med_pct[w]), replace = T)
    variant_results_med_miscalled <- c(variant_results_med_miscalled,z - sum(med_correct))
    variant_results_variant_num <- c(variant_results_variant_num, z)
    variant_results_replicate_num <- c(variant_results_replicate_num, multiverse_date_frame_summary$replicate[w])
  }
}

variant_ranges_date_frame <- data.frame("variants" = variant_results_variant_num, "replicates" = variant_results_replicate_num, "low_miscall" = variant_results_low_miscalled, "med_miscall" = variant_results_med_miscalled)
variant_ranges_date_frame$variants <- as.factor(variant_ranges_date_frame$variants)

Sortseq_variants_replicates_plot <- ggplot() + 
  theme(panel.grid.major.x = element_blank(), panel.grid.minor = element_blank()) + 
  labs(x = "Number of replicate experiments", y = "Number of variants being tested", title = "Number of incorrectly called variants\n(blue is low scores, red is medium scores)") + 
  geom_text(data = variant_ranges_date_frame, aes(x = replicates, y = variants, label = low_miscall), nudge_y = 0.2, color = "blue") +
  geom_text(data = variant_ranges_date_frame, aes(x = replicates, y = variants, label = med_miscall), nudge_y = -0.2, color = "red")
Sortseq_variants_replicates_plot
ggsave(file = "Plots/Sortseq_variants_replicates_plot.pdf", Sortseq_variants_replicates_plot, height = 4, width = 5)

```


