---
title: "Nextseq_mixing"
author: "Kenneth Matreyek"
date: '2022-10-05'
output: html_document
---

```{r Import packages}
rm(list = ls())
library(tidyverse)
library(patchwork)
library(googlesheets4)
set.seed(1234567)
theme_set(theme_bw())
theme_update(legend.title = element_blank())
```

### This is for NextSeq Kit 4
```{r Import data}
samples <- read_sheet("https://docs.google.com/spreadsheets/d/1_JNV3crx33WMexKpFgCle54Ftxx1pqIQAT00_gy120U/edit?usp=sharing", sheet = "NextSeq4") 
#colnames(samples)[23] <- "concentration"
samples$concentration <- as.numeric(as.character((samples$concentration)))

ggplot() + geom_histogram(data = samples, aes(x = concentration), binwidth = 5,  fill = "grey50", color = "black") + 
  facet_grid(rows = vars(amp_group)) + geom_vline(xintercept = c(10,40), linetype = 2, alpha = 0.4)

amp3_set1 <- samples %>% filter(amp_group == 3 & concentration < 10 )
amp3_set2 <- samples %>% filter(amp_group == 3 & concentration > 10 & concentration < 40)
amp3_set3 <- samples %>% filter(amp_group == 3 & concentration > 40)
```

```{r Calculating mixing for Amp set 3 (ACE2 dBC samples)}
amp3_set1$dil_ng <- 24  ### I manually adjusted this number
amp3_set1$dil_vol <- round(amp3_set1$dil_ng / amp3_set1$concentration,2)
amp3_set1$mix_group <- "1A"
amp3_set1[amp3_set1$dil_vol == "Inf","dil_vol"] <- 0

amp3_set2$dil_ng <- 50  ### I manually adjusted this number
amp3_set2$dil_vol <- round(amp3_set2$dil_ng / amp3_set2$concentration,2)
amp3_set2$mix_group <- "1B"

amp3_set3$dil_ng <- 100  ### I manually adjusted this number
amp3_set3$dil_vol <- round(amp3_set3$dil_ng / amp3_set3$concentration,2)
amp3_set3$mix_group <- "1C"

amp3_mix_table <- data.frame("sample" = c("amp3_set1","amp3_set2","amp3_set3"),
                             "conc" = c(sum(amp3_set1$dil_ng) / sum(amp3_set1$dil_vol),
                                        sum(amp3_set2$dil_ng) / sum(amp3_set2$dil_vol),
                                        sum(amp3_set3$dil_ng) / sum(amp3_set3$dil_vol)),
                             "vol" = c(sum(amp3_set1$dil_vol),
                                       sum(amp3_set2$dil_vol),
                                       sum(amp3_set3$dil_vol)))

amp3_mix_volumes <- c(18,5.2,1.5)  ### I manually adjusted these to get the desired final concentrations
amp3_mix_table$mix_vol <- amp3_mix_volumes
total_amp3_volume <- sum(amp3_mix_table$mix_vol)

paste("The total volume of the amp1 mix is:",round(total_amp3_volume,2))
paste("The amp3 set1 final conc is:",round(amp3_mix_table$conc[1] * amp3_mix_table$mix_vol[1] / total_amp3_volume,2))
paste("The amp3 set2 final conc is:",round(amp3_mix_table$conc[2] * amp3_mix_table$mix_vol[2] / total_amp3_volume,2))
paste("The amp3 set3 final conc is:",round(amp3_mix_table$conc[3] * amp3_mix_table$mix_vol[3] / total_amp3_volume,2))


columns_for_export <- c("pcr_tube_label", "mix_group", "dil_vol")

amp3_for_export <- rbind(amp3_set1[,columns_for_export],amp3_set2[,columns_for_export],amp3_set3[,columns_for_export]) %>% arrange(pcr_tube_label)

write.csv(file = "Nextseq4/amp3_individual_mixing.csv", amp3_for_export, row.names = FALSE)
write.csv(file = "Nextseq4/amp3_grouped_mixing_table.csv", amp3_mix_table, row.names = FALSE)

```





### This was for NextSeq Kit 3
```{r Import data}
samples <- read_sheet("https://docs.google.com/spreadsheets/d/1_JNV3crx33WMexKpFgCle54Ftxx1pqIQAT00_gy120U/edit?usp=sharing", sheet = "NextSeq3_101022") 
#colnames(samples)[23] <- "concentration"
samples$concentration <- as.numeric(as.character((samples$concentration)))

ggplot() + geom_histogram(data = samples, aes(x = concentration), binwidth = 5,  fill = "grey50", color = "black") + 
  facet_grid(rows = vars(amp_group)) + geom_vline(xintercept = c(10,40), linetype = 2, alpha = 0.4)

amp1_set1 <- samples %>% filter(amp_group == 1 & concentration < 10 )
amp1_set2 <- samples %>% filter(amp_group == 1 & concentration > 10 & concentration < 40)
amp1_set3 <- samples %>% filter(amp_group == 1 & concentration > 40)
amp2 <- samples %>% filter(amp_group == 2)
```


```{r Calculating mixing for Amp set 1}
amp1_set1$dil_ng <- 14
amp1_set1$dil_vol <- round(amp1_set1$dil_ng / amp1_set1$concentration,2)
amp1_set1$mix_group <- "1A"
amp1_set1[amp1_set1$dil_vol == "Inf","dil_vol"] <- 0

amp1_set2$dil_ng <- 50
amp1_set2$dil_vol <- round(amp1_set2$dil_ng / amp1_set2$concentration,2)
amp1_set2$mix_group <- "1B"

amp1_set3$dil_ng <- 100
amp1_set3$dil_vol <- round(amp1_set3$dil_ng / amp1_set3$concentration,2)
amp1_set3$mix_group <- "1C"

amp1_mix_table <- data.frame("sample" = c("amp1_set1","amp1_set2","amp1_set3"),
                             "conc" = c(sum(amp1_set1$dil_ng) / sum(amp1_set1$dil_vol),
                                        sum(amp1_set2$dil_ng) / sum(amp1_set2$dil_vol),
                                        sum(amp1_set3$dil_ng) / sum(amp1_set3$dil_vol)),
                             "vol" = c(sum(amp1_set1$dil_vol),
                                       sum(amp1_set2$dil_vol),
                                       sum(amp1_set3$dil_vol)))

amp1_mix_volumes <- c(17,3.3,1.1)
amp1_mix_table$mix_vol <- amp1_mix_volumes
total_amp1_volume <- sum(amp1_mix_table$mix_vol)

paste("The total volume of the amp1 mix is:",round(total_amp1_volume,2))
paste("The amp1 set1 final conc is:",round(amp1_mix_table$conc[1] * amp1_mix_table$mix_vol[1] / total_amp1_volume,2))
paste("The amp1 set2 final conc is:",round(amp1_mix_table$conc[2] * amp1_mix_table$mix_vol[2] / total_amp1_volume,2))
paste("The amp1 set3 final conc is:",round(amp1_mix_table$conc[3] * amp1_mix_table$mix_vol[3] / total_amp1_volume,2))


columns_for_export <- c("pcr_tube_label", "mix_group", "dil_vol")

amp1_for_export <- rbind(amp1_set1[,columns_for_export],amp1_set2[,columns_for_export],amp1_set3[,columns_for_export]) %>% arrange(pcr_tube_label)

write.csv(file = "amp1_individual_mixing.csv", amp1_for_export, row.names = FALSE)
write.csv(file = "amp1_grouped_mixing_table.csv", amp1_mix_table, row.names = FALSE)

```


```{r Calculating mixing for Amp set 2}

amp2$dil_ng <- 100
amp2$dil_vol <- round(amp2$dil_ng / amp2$concentration,2)
amp2$mix_group <- "2"

amp2_mix_table <- data.frame("sample" = c("amp2", "water"),
                             "conc" = c(sum(amp2$dil_ng) / sum(amp2$dil_vol, na.rm = T), 0),
                             "vol" = c(sum(amp2$dil_vol, na.rm = T), 50))

amp2_mix_volumes <- c(10,30)
amp2_mix_table$mix_vol <- amp2_mix_volumes
total_amp2_volume <- sum(amp2_mix_table$mix_vol)

paste("The total volume of the amp2 mix is:",round(total_amp2_volume,2))
paste("The amp2 final conc is:",round(amp2_mix_table$conc[1] * amp2_mix_table$mix_vol[1] / amp2_mix_volumes,2))

amp2_for_export <- amp2[,columns_for_export] %>% arrange(pcr_tube_label)

write.csv(file = "amp2_individual_mixing.csv", amp2_for_export, row.names = FALSE)
```



